import {
  Activity,
  Users,
  Flame,
  ShieldAlert,
  GitCommit,
  Car,
  Clock,
  UsersRound,
  PackageX,
  BoxSelect,
  Truck,
  HardHat,
} from 'lucide-react'

export const mockAnalytics = [
  {
    id: 'a1',
    name: 'Detecção de Movimento Inteligente',
    price: 15.0,
    icon: Activity,
    desc: 'Diferencia pessoas e veículos de ruídos visuais.',
    color: 'text-green-500',
  },
  {
    id: 'a2',
    name: 'Contagem de Pessoas (People Counting)',
    price: 45.0,
    icon: Users,
    desc: 'Contagem de entradas/saídas e fluxo por período.',
    color: 'text-blue-500',
  },
  {
    id: 'a3',
    name: 'Mapa de Calor (Heatmap)',
    price: 60.0,
    icon: Flame,
    desc: 'Identifica áreas de maior tráfego e interesse.',
    color: 'text-orange-500',
  },
  {
    id: 'a4',
    name: 'Detecção de Intrusão',
    price: 35.0,
    icon: ShieldAlert,
    desc: 'Alertas imediatos para invasões de áreas restritas.',
    color: 'text-red-500',
  },
  {
    id: 'a5',
    name: 'Cruzamento de Linha (Line Crossing)',
    price: 25.0,
    icon: GitCommit,
    desc: 'Detecção direcional em linhas virtuais cruzadas.',
    color: 'text-purple-500',
  },
  {
    id: 'a6',
    name: 'Reconhecimento de Placas (LPR/ANPR)',
    price: 120.0,
    icon: Car,
    desc: 'Leitura e registro automático de placas veiculares.',
    color: 'text-cyan-500',
  },
  {
    id: 'a7',
    name: 'Detecção de Permanência (Loitering)',
    price: 40.0,
    icon: Clock,
    desc: 'Identifica pessoas paradas de forma suspeita.',
    color: 'text-yellow-500',
  },
  {
    id: 'a8',
    name: 'Detecção de Aglomeração',
    price: 55.0,
    icon: UsersRound,
    desc: 'Contagem simultânea para evitar superlotação.',
    color: 'text-pink-500',
  },
  {
    id: 'a9',
    name: 'Detecção de Objetos Abandonados',
    price: 45.0,
    icon: PackageX,
    desc: 'Identifica itens suspeitos deixados no local.',
    color: 'text-indigo-500',
  },
  {
    id: 'a10',
    name: 'Detecção de Remoção de Objetos',
    price: 45.0,
    icon: BoxSelect,
    desc: 'Alerta quando itens valiosos são retirados.',
    color: 'text-teal-500',
  },
  {
    id: 'a11',
    name: 'Classificação de Veículos',
    price: 80.0,
    icon: Truck,
    desc: 'Diferencia carros, motos, ônibus e caminhões.',
    color: 'text-emerald-500',
  },
  {
    id: 'a12',
    name: 'Detecção de Uso de EPI',
    price: 90.0,
    icon: HardHat,
    desc: 'Verifica uso obrigatório de capacetes e coletes.',
    color: 'text-amber-500',
  },
]

export const mockCameras = [
  {
    id: 'c1',
    name: 'Portão Principal',
    location: 'Externa',
    status: 'online',
    image: 'https://img.usecurling.com/p/400/225?q=gate&color=blue',
    analytics: ['a1', 'a6', 'a4'],
  },
  {
    id: 'c2',
    name: 'Recepção Leste',
    location: 'Interna',
    status: 'online',
    image: 'https://img.usecurling.com/p/400/225?q=lobby&color=blue',
    analytics: ['a2', 'a3'],
  },
  {
    id: 'c3',
    name: 'Estacionamento G1',
    location: 'Externa',
    status: 'offline',
    image: 'https://img.usecurling.com/p/400/225?q=parking&color=gray',
    analytics: ['a11', 'a6'],
  },
  {
    id: 'c4',
    name: 'Corredor A',
    location: 'Interna',
    status: 'online',
    image: 'https://img.usecurling.com/p/400/225?q=hallway&color=blue',
    analytics: ['a7', 'a9'],
  },
  {
    id: 'c5',
    name: 'Área de Carga',
    location: 'Externa',
    status: 'online',
    image: 'https://img.usecurling.com/p/400/225?q=warehouse&color=blue',
    analytics: ['a12', 'a4'],
  },
  {
    id: 'c6',
    name: 'Loja Principal',
    location: 'Interna',
    status: 'online',
    image: 'https://img.usecurling.com/p/400/225?q=retail&color=blue',
    analytics: ['a2', 'a3', 'a8'],
  },
]

export const mockEvents = [
  {
    id: 'e1',
    time: '14:32:05',
    type: 'Veículo Detectado',
    camera: 'Estacionamento G1',
    severity: 'info',
    image: 'https://img.usecurling.com/p/150/100?q=car',
  },
  {
    id: 'e2',
    time: '14:30:12',
    type: 'Intrusão Perímetro',
    camera: 'Portão Principal',
    severity: 'critical',
    image: 'https://img.usecurling.com/p/150/100?q=intruder',
  },
  {
    id: 'e3',
    time: '14:15:00',
    type: 'Aglomeração Alta',
    camera: 'Recepção Leste',
    severity: 'warning',
    image: 'https://img.usecurling.com/p/150/100?q=crowd',
  },
  {
    id: 'e4',
    time: '14:02:45',
    type: 'Falta de EPI',
    camera: 'Área de Carga',
    severity: 'warning',
    image: 'https://img.usecurling.com/p/150/100?q=worker',
  },
  {
    id: 'e5',
    time: '13:55:20',
    type: 'Movimento Suspeito',
    camera: 'Corredor A',
    severity: 'info',
    image: 'https://img.usecurling.com/p/150/100?q=hallway',
  },
]
